// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_MATCHERS_SCHEMA_H_
#define FLATBUFFERS_GENERATED_MATCHERS_SCHEMA_H_

#include "flatbuffers/flatbuffers.h"

// Ensure the included flatbuffers.h is the same version as when this file was
// generated, otherwise it may not be compatible.
static_assert(FLATBUFFERS_VERSION_MAJOR == 23 &&
              FLATBUFFERS_VERSION_MINOR == 5 &&
              FLATBUFFERS_VERSION_REVISION == 26,
             "Non-compatible flatbuffers version included");

#include "encode_value_generated.h"
#include "enums_generated.h"
#include "ranges_generated.h"

namespace schema {

struct StringMatcher;
struct StringMatcherBuilder;

struct AccessFlagsMatcher;
struct AccessFlagsMatcherBuilder;

struct TargetElementTypesMatcher;
struct TargetElementTypesMatcherBuilder;

struct AnnotationElementsMatcher;
struct AnnotationElementsMatcherBuilder;

struct AnnotationMatcher;
struct AnnotationMatcherBuilder;

struct AnnotationsMatcher;
struct AnnotationsMatcherBuilder;

struct ParameterMatcher;
struct ParameterMatcherBuilder;

struct ParametersMatcher;
struct ParametersMatcherBuilder;

struct OpCodesMatcher;
struct OpCodesMatcherBuilder;

struct UsingFieldMatcher;
struct UsingFieldMatcherBuilder;

struct UsingNumberMatcher;
struct UsingNumberMatcherBuilder;

struct MethodMatcher;
struct MethodMatcherBuilder;

struct MethodsMatcher;
struct MethodsMatcherBuilder;

struct InterfacesMatcher;
struct InterfacesMatcherBuilder;

struct FieldMatcher;
struct FieldMatcherBuilder;

struct FieldsMatcher;
struct FieldsMatcherBuilder;

struct ClassMatcher;
struct ClassMatcherBuilder;

struct BatchUsingStringsMatcher;
struct BatchUsingStringsMatcherBuilder;

enum class AnnotationElementValueMatcher : uint8_t {
  NONE = 0,
  EncodeValueBoolean = 1,
  EncodeValueByte = 2,
  EncodeValueShort = 3,
  EncodeValueChar = 4,
  EncodeValueInt = 5,
  EncodeValueLong = 6,
  EncodeValueFloat = 7,
  EncodeValueDouble = 8,
  StringMatcher = 9,
  ClassMatcher = 10,
  AnnotationElementsMatcher = 11,
  AnnotationMatcher = 12,
  MIN = NONE,
  MAX = AnnotationMatcher
};

inline const AnnotationElementValueMatcher (&EnumValuesAnnotationElementValueMatcher())[13] {
  static const AnnotationElementValueMatcher values[] = {
    AnnotationElementValueMatcher::NONE,
    AnnotationElementValueMatcher::EncodeValueBoolean,
    AnnotationElementValueMatcher::EncodeValueByte,
    AnnotationElementValueMatcher::EncodeValueShort,
    AnnotationElementValueMatcher::EncodeValueChar,
    AnnotationElementValueMatcher::EncodeValueInt,
    AnnotationElementValueMatcher::EncodeValueLong,
    AnnotationElementValueMatcher::EncodeValueFloat,
    AnnotationElementValueMatcher::EncodeValueDouble,
    AnnotationElementValueMatcher::StringMatcher,
    AnnotationElementValueMatcher::ClassMatcher,
    AnnotationElementValueMatcher::AnnotationElementsMatcher,
    AnnotationElementValueMatcher::AnnotationMatcher
  };
  return values;
}

inline const char * const *EnumNamesAnnotationElementValueMatcher() {
  static const char * const names[14] = {
    "NONE",
    "EncodeValueBoolean",
    "EncodeValueByte",
    "EncodeValueShort",
    "EncodeValueChar",
    "EncodeValueInt",
    "EncodeValueLong",
    "EncodeValueFloat",
    "EncodeValueDouble",
    "StringMatcher",
    "ClassMatcher",
    "AnnotationElementsMatcher",
    "AnnotationMatcher",
    nullptr
  };
  return names;
}

inline const char *EnumNameAnnotationElementValueMatcher(AnnotationElementValueMatcher e) {
  if (::flatbuffers::IsOutRange(e, AnnotationElementValueMatcher::NONE, AnnotationElementValueMatcher::AnnotationMatcher)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesAnnotationElementValueMatcher()[index];
}

template<typename T> struct AnnotationElementValueMatcherTraits {
  static const AnnotationElementValueMatcher enum_value = AnnotationElementValueMatcher::NONE;
};

template<> struct AnnotationElementValueMatcherTraits<schema::EncodeValueBoolean> {
  static const AnnotationElementValueMatcher enum_value = AnnotationElementValueMatcher::EncodeValueBoolean;
};

template<> struct AnnotationElementValueMatcherTraits<schema::EncodeValueByte> {
  static const AnnotationElementValueMatcher enum_value = AnnotationElementValueMatcher::EncodeValueByte;
};

template<> struct AnnotationElementValueMatcherTraits<schema::EncodeValueShort> {
  static const AnnotationElementValueMatcher enum_value = AnnotationElementValueMatcher::EncodeValueShort;
};

template<> struct AnnotationElementValueMatcherTraits<schema::EncodeValueChar> {
  static const AnnotationElementValueMatcher enum_value = AnnotationElementValueMatcher::EncodeValueChar;
};

template<> struct AnnotationElementValueMatcherTraits<schema::EncodeValueInt> {
  static const AnnotationElementValueMatcher enum_value = AnnotationElementValueMatcher::EncodeValueInt;
};

template<> struct AnnotationElementValueMatcherTraits<schema::EncodeValueLong> {
  static const AnnotationElementValueMatcher enum_value = AnnotationElementValueMatcher::EncodeValueLong;
};

template<> struct AnnotationElementValueMatcherTraits<schema::EncodeValueFloat> {
  static const AnnotationElementValueMatcher enum_value = AnnotationElementValueMatcher::EncodeValueFloat;
};

template<> struct AnnotationElementValueMatcherTraits<schema::EncodeValueDouble> {
  static const AnnotationElementValueMatcher enum_value = AnnotationElementValueMatcher::EncodeValueDouble;
};

template<> struct AnnotationElementValueMatcherTraits<schema::StringMatcher> {
  static const AnnotationElementValueMatcher enum_value = AnnotationElementValueMatcher::StringMatcher;
};

template<> struct AnnotationElementValueMatcherTraits<schema::ClassMatcher> {
  static const AnnotationElementValueMatcher enum_value = AnnotationElementValueMatcher::ClassMatcher;
};

template<> struct AnnotationElementValueMatcherTraits<schema::AnnotationElementsMatcher> {
  static const AnnotationElementValueMatcher enum_value = AnnotationElementValueMatcher::AnnotationElementsMatcher;
};

template<> struct AnnotationElementValueMatcherTraits<schema::AnnotationMatcher> {
  static const AnnotationElementValueMatcher enum_value = AnnotationElementValueMatcher::AnnotationMatcher;
};

bool VerifyAnnotationElementValueMatcher(::flatbuffers::Verifier &verifier, const void *obj, AnnotationElementValueMatcher type);
bool VerifyAnnotationElementValueMatcherVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<AnnotationElementValueMatcher> *types);

enum class Number : uint8_t {
  NONE = 0,
  EncodeValueShort = 1,
  EncodeValueInt = 2,
  EncodeValueLong = 3,
  EncodeValueFloat = 4,
  EncodeValueDouble = 5,
  MIN = NONE,
  MAX = EncodeValueDouble
};

inline const Number (&EnumValuesNumber())[6] {
  static const Number values[] = {
    Number::NONE,
    Number::EncodeValueShort,
    Number::EncodeValueInt,
    Number::EncodeValueLong,
    Number::EncodeValueFloat,
    Number::EncodeValueDouble
  };
  return values;
}

inline const char * const *EnumNamesNumber() {
  static const char * const names[7] = {
    "NONE",
    "EncodeValueShort",
    "EncodeValueInt",
    "EncodeValueLong",
    "EncodeValueFloat",
    "EncodeValueDouble",
    nullptr
  };
  return names;
}

inline const char *EnumNameNumber(Number e) {
  if (::flatbuffers::IsOutRange(e, Number::NONE, Number::EncodeValueDouble)) return "";
  const size_t index = static_cast<size_t>(e);
  return EnumNamesNumber()[index];
}

template<typename T> struct NumberTraits {
  static const Number enum_value = Number::NONE;
};

template<> struct NumberTraits<schema::EncodeValueShort> {
  static const Number enum_value = Number::EncodeValueShort;
};

template<> struct NumberTraits<schema::EncodeValueInt> {
  static const Number enum_value = Number::EncodeValueInt;
};

template<> struct NumberTraits<schema::EncodeValueLong> {
  static const Number enum_value = Number::EncodeValueLong;
};

template<> struct NumberTraits<schema::EncodeValueFloat> {
  static const Number enum_value = Number::EncodeValueFloat;
};

template<> struct NumberTraits<schema::EncodeValueDouble> {
  static const Number enum_value = Number::EncodeValueDouble;
};

bool VerifyNumber(::flatbuffers::Verifier &verifier, const void *obj, Number type);
bool VerifyNumberVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<Number> *types);

struct StringMatcher FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef StringMatcherBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TYPE = 4,
    VT_VALUE = 6
  };
  schema::StringMatchType type() const {
    return static_cast<schema::StringMatchType>(GetField<int8_t>(VT_TYPE, 0));
  }
  const ::flatbuffers::String *value() const {
    return GetPointer<const ::flatbuffers::String *>(VT_VALUE);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int8_t>(verifier, VT_TYPE, 1) &&
           VerifyOffset(verifier, VT_VALUE) &&
           verifier.VerifyString(value()) &&
           verifier.EndTable();
  }
};

struct StringMatcherBuilder {
  typedef StringMatcher Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_type(schema::StringMatchType type) {
    fbb_.AddElement<int8_t>(StringMatcher::VT_TYPE, static_cast<int8_t>(type), 0);
  }
  void add_value(::flatbuffers::Offset<::flatbuffers::String> value) {
    fbb_.AddOffset(StringMatcher::VT_VALUE, value);
  }
  explicit StringMatcherBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<StringMatcher> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<StringMatcher>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<StringMatcher> CreateStringMatcher(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    schema::StringMatchType type = schema::StringMatchType::Contains,
    ::flatbuffers::Offset<::flatbuffers::String> value = 0) {
  StringMatcherBuilder builder_(_fbb);
  builder_.add_value(value);
  builder_.add_type(type);
  return builder_.Finish();
}

struct StringMatcher::Traits {
  using type = StringMatcher;
  static auto constexpr Create = CreateStringMatcher;
};

inline ::flatbuffers::Offset<StringMatcher> CreateStringMatcherDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    schema::StringMatchType type = schema::StringMatchType::Contains,
    const char *value = nullptr) {
  auto value__ = value ? _fbb.CreateString(value) : 0;
  return schema::CreateStringMatcher(
      _fbb,
      type,
      value__);
}

struct AccessFlagsMatcher FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef AccessFlagsMatcherBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_MATCH_TYPE = 4,
    VT_FLAGS = 6
  };
  schema::MatchType match_type() const {
    return static_cast<schema::MatchType>(GetField<int8_t>(VT_MATCH_TYPE, 0));
  }
  uint32_t flags() const {
    return GetField<uint32_t>(VT_FLAGS, 0);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int8_t>(verifier, VT_MATCH_TYPE, 1) &&
           VerifyField<uint32_t>(verifier, VT_FLAGS, 4) &&
           verifier.EndTable();
  }
};

struct AccessFlagsMatcherBuilder {
  typedef AccessFlagsMatcher Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_match_type(schema::MatchType match_type) {
    fbb_.AddElement<int8_t>(AccessFlagsMatcher::VT_MATCH_TYPE, static_cast<int8_t>(match_type), 0);
  }
  void add_flags(uint32_t flags) {
    fbb_.AddElement<uint32_t>(AccessFlagsMatcher::VT_FLAGS, flags, 0);
  }
  explicit AccessFlagsMatcherBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<AccessFlagsMatcher> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<AccessFlagsMatcher>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<AccessFlagsMatcher> CreateAccessFlagsMatcher(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    schema::MatchType match_type = schema::MatchType::Contain,
    uint32_t flags = 0) {
  AccessFlagsMatcherBuilder builder_(_fbb);
  builder_.add_flags(flags);
  builder_.add_match_type(match_type);
  return builder_.Finish();
}

struct AccessFlagsMatcher::Traits {
  using type = AccessFlagsMatcher;
  static auto constexpr Create = CreateAccessFlagsMatcher;
};

struct TargetElementTypesMatcher FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef TargetElementTypesMatcherBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_MATCH_TYPE = 4,
    VT_TYPES = 6
  };
  schema::MatchType match_type() const {
    return static_cast<schema::MatchType>(GetField<int8_t>(VT_MATCH_TYPE, 0));
  }
  const ::flatbuffers::Vector<schema::TargetElementType> *types() const {
    return GetPointer<const ::flatbuffers::Vector<schema::TargetElementType> *>(VT_TYPES);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int8_t>(verifier, VT_MATCH_TYPE, 1) &&
           VerifyOffset(verifier, VT_TYPES) &&
           verifier.VerifyVector(types()) &&
           verifier.EndTable();
  }
};

struct TargetElementTypesMatcherBuilder {
  typedef TargetElementTypesMatcher Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_match_type(schema::MatchType match_type) {
    fbb_.AddElement<int8_t>(TargetElementTypesMatcher::VT_MATCH_TYPE, static_cast<int8_t>(match_type), 0);
  }
  void add_types(::flatbuffers::Offset<::flatbuffers::Vector<schema::TargetElementType>> types) {
    fbb_.AddOffset(TargetElementTypesMatcher::VT_TYPES, types);
  }
  explicit TargetElementTypesMatcherBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<TargetElementTypesMatcher> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<TargetElementTypesMatcher>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<TargetElementTypesMatcher> CreateTargetElementTypesMatcher(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    schema::MatchType match_type = schema::MatchType::Contain,
    ::flatbuffers::Offset<::flatbuffers::Vector<schema::TargetElementType>> types = 0) {
  TargetElementTypesMatcherBuilder builder_(_fbb);
  builder_.add_types(types);
  builder_.add_match_type(match_type);
  return builder_.Finish();
}

struct TargetElementTypesMatcher::Traits {
  using type = TargetElementTypesMatcher;
  static auto constexpr Create = CreateTargetElementTypesMatcher;
};

inline ::flatbuffers::Offset<TargetElementTypesMatcher> CreateTargetElementTypesMatcherDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    schema::MatchType match_type = schema::MatchType::Contain,
    const std::vector<schema::TargetElementType> *types = nullptr) {
  auto types__ = types ? _fbb.CreateVector<schema::TargetElementType>(*types) : 0;
  return schema::CreateTargetElementTypesMatcher(
      _fbb,
      match_type,
      types__);
}

struct AnnotationElementsMatcher FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef AnnotationElementsMatcherBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_VALUE_COUNT = 4,
    VT_MATCH_TYPE = 6,
    VT_VALUES_TYPE = 8,
    VT_VALUES = 10
  };
  const schema::IntRange *value_count() const {
    return GetPointer<const schema::IntRange *>(VT_VALUE_COUNT);
  }
  schema::MatchType match_type() const {
    return static_cast<schema::MatchType>(GetField<int8_t>(VT_MATCH_TYPE, 0));
  }
  const ::flatbuffers::Vector<schema::AnnotationElementValueMatcher> *values_type() const {
    return GetPointer<const ::flatbuffers::Vector<schema::AnnotationElementValueMatcher> *>(VT_VALUES_TYPE);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *>(VT_VALUES);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_VALUE_COUNT) &&
           verifier.VerifyTable(value_count()) &&
           VerifyField<int8_t>(verifier, VT_MATCH_TYPE, 1) &&
           VerifyOffset(verifier, VT_VALUES_TYPE) &&
           verifier.VerifyVector(values_type()) &&
           VerifyOffset(verifier, VT_VALUES) &&
           verifier.VerifyVector(values()) &&
           VerifyAnnotationElementValueMatcherVector(verifier, values(), values_type()) &&
           verifier.EndTable();
  }
};

struct AnnotationElementsMatcherBuilder {
  typedef AnnotationElementsMatcher Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_value_count(::flatbuffers::Offset<schema::IntRange> value_count) {
    fbb_.AddOffset(AnnotationElementsMatcher::VT_VALUE_COUNT, value_count);
  }
  void add_match_type(schema::MatchType match_type) {
    fbb_.AddElement<int8_t>(AnnotationElementsMatcher::VT_MATCH_TYPE, static_cast<int8_t>(match_type), 0);
  }
  void add_values_type(::flatbuffers::Offset<::flatbuffers::Vector<schema::AnnotationElementValueMatcher>> values_type) {
    fbb_.AddOffset(AnnotationElementsMatcher::VT_VALUES_TYPE, values_type);
  }
  void add_values(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<void>>> values) {
    fbb_.AddOffset(AnnotationElementsMatcher::VT_VALUES, values);
  }
  explicit AnnotationElementsMatcherBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<AnnotationElementsMatcher> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<AnnotationElementsMatcher>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<AnnotationElementsMatcher> CreateAnnotationElementsMatcher(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<schema::IntRange> value_count = 0,
    schema::MatchType match_type = schema::MatchType::Contain,
    ::flatbuffers::Offset<::flatbuffers::Vector<schema::AnnotationElementValueMatcher>> values_type = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<void>>> values = 0) {
  AnnotationElementsMatcherBuilder builder_(_fbb);
  builder_.add_values(values);
  builder_.add_values_type(values_type);
  builder_.add_value_count(value_count);
  builder_.add_match_type(match_type);
  return builder_.Finish();
}

struct AnnotationElementsMatcher::Traits {
  using type = AnnotationElementsMatcher;
  static auto constexpr Create = CreateAnnotationElementsMatcher;
};

inline ::flatbuffers::Offset<AnnotationElementsMatcher> CreateAnnotationElementsMatcherDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<schema::IntRange> value_count = 0,
    schema::MatchType match_type = schema::MatchType::Contain,
    const std::vector<schema::AnnotationElementValueMatcher> *values_type = nullptr,
    const std::vector<::flatbuffers::Offset<void>> *values = nullptr) {
  auto values_type__ = values_type ? _fbb.CreateVector<schema::AnnotationElementValueMatcher>(*values_type) : 0;
  auto values__ = values ? _fbb.CreateVector<::flatbuffers::Offset<void>>(*values) : 0;
  return schema::CreateAnnotationElementsMatcher(
      _fbb,
      value_count,
      match_type,
      values_type__,
      values__);
}

struct AnnotationMatcher FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef AnnotationMatcherBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_TYPE_CLASS = 4,
    VT_TARGET_ELEMENT_TYPES = 6,
    VT_POLICY = 8,
    VT_ANNOTATIONS = 10
  };
  const schema::ClassMatcher *type_class() const {
    return GetPointer<const schema::ClassMatcher *>(VT_TYPE_CLASS);
  }
  const schema::TargetElementTypesMatcher *target_element_types() const {
    return GetPointer<const schema::TargetElementTypesMatcher *>(VT_TARGET_ELEMENT_TYPES);
  }
  schema::RetentionPolicyType policy() const {
    return static_cast<schema::RetentionPolicyType>(GetField<int8_t>(VT_POLICY, 0));
  }
  const schema::AnnotationsMatcher *annotations() const {
    return GetPointer<const schema::AnnotationsMatcher *>(VT_ANNOTATIONS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_TYPE_CLASS) &&
           verifier.VerifyTable(type_class()) &&
           VerifyOffset(verifier, VT_TARGET_ELEMENT_TYPES) &&
           verifier.VerifyTable(target_element_types()) &&
           VerifyField<int8_t>(verifier, VT_POLICY, 1) &&
           VerifyOffset(verifier, VT_ANNOTATIONS) &&
           verifier.VerifyTable(annotations()) &&
           verifier.EndTable();
  }
};

struct AnnotationMatcherBuilder {
  typedef AnnotationMatcher Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_type_class(::flatbuffers::Offset<schema::ClassMatcher> type_class) {
    fbb_.AddOffset(AnnotationMatcher::VT_TYPE_CLASS, type_class);
  }
  void add_target_element_types(::flatbuffers::Offset<schema::TargetElementTypesMatcher> target_element_types) {
    fbb_.AddOffset(AnnotationMatcher::VT_TARGET_ELEMENT_TYPES, target_element_types);
  }
  void add_policy(schema::RetentionPolicyType policy) {
    fbb_.AddElement<int8_t>(AnnotationMatcher::VT_POLICY, static_cast<int8_t>(policy), 0);
  }
  void add_annotations(::flatbuffers::Offset<schema::AnnotationsMatcher> annotations) {
    fbb_.AddOffset(AnnotationMatcher::VT_ANNOTATIONS, annotations);
  }
  explicit AnnotationMatcherBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<AnnotationMatcher> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<AnnotationMatcher>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<AnnotationMatcher> CreateAnnotationMatcher(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<schema::ClassMatcher> type_class = 0,
    ::flatbuffers::Offset<schema::TargetElementTypesMatcher> target_element_types = 0,
    schema::RetentionPolicyType policy = schema::RetentionPolicyType::Source,
    ::flatbuffers::Offset<schema::AnnotationsMatcher> annotations = 0) {
  AnnotationMatcherBuilder builder_(_fbb);
  builder_.add_annotations(annotations);
  builder_.add_target_element_types(target_element_types);
  builder_.add_type_class(type_class);
  builder_.add_policy(policy);
  return builder_.Finish();
}

struct AnnotationMatcher::Traits {
  using type = AnnotationMatcher;
  static auto constexpr Create = CreateAnnotationMatcher;
};

struct AnnotationsMatcher FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef AnnotationsMatcherBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ANNOTAION_COUNT = 4,
    VT_MATCH_TYPE = 6,
    VT_ANNOTATIONS = 8
  };
  const schema::IntRange *annotaion_count() const {
    return GetPointer<const schema::IntRange *>(VT_ANNOTAION_COUNT);
  }
  schema::MatchType match_type() const {
    return static_cast<schema::MatchType>(GetField<int8_t>(VT_MATCH_TYPE, 0));
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<schema::AnnotationMatcher>> *annotations() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<schema::AnnotationMatcher>> *>(VT_ANNOTATIONS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ANNOTAION_COUNT) &&
           verifier.VerifyTable(annotaion_count()) &&
           VerifyField<int8_t>(verifier, VT_MATCH_TYPE, 1) &&
           VerifyOffset(verifier, VT_ANNOTATIONS) &&
           verifier.VerifyVector(annotations()) &&
           verifier.VerifyVectorOfTables(annotations()) &&
           verifier.EndTable();
  }
};

struct AnnotationsMatcherBuilder {
  typedef AnnotationsMatcher Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_annotaion_count(::flatbuffers::Offset<schema::IntRange> annotaion_count) {
    fbb_.AddOffset(AnnotationsMatcher::VT_ANNOTAION_COUNT, annotaion_count);
  }
  void add_match_type(schema::MatchType match_type) {
    fbb_.AddElement<int8_t>(AnnotationsMatcher::VT_MATCH_TYPE, static_cast<int8_t>(match_type), 0);
  }
  void add_annotations(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<schema::AnnotationMatcher>>> annotations) {
    fbb_.AddOffset(AnnotationsMatcher::VT_ANNOTATIONS, annotations);
  }
  explicit AnnotationsMatcherBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<AnnotationsMatcher> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<AnnotationsMatcher>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<AnnotationsMatcher> CreateAnnotationsMatcher(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<schema::IntRange> annotaion_count = 0,
    schema::MatchType match_type = schema::MatchType::Contain,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<schema::AnnotationMatcher>>> annotations = 0) {
  AnnotationsMatcherBuilder builder_(_fbb);
  builder_.add_annotations(annotations);
  builder_.add_annotaion_count(annotaion_count);
  builder_.add_match_type(match_type);
  return builder_.Finish();
}

struct AnnotationsMatcher::Traits {
  using type = AnnotationsMatcher;
  static auto constexpr Create = CreateAnnotationsMatcher;
};

inline ::flatbuffers::Offset<AnnotationsMatcher> CreateAnnotationsMatcherDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<schema::IntRange> annotaion_count = 0,
    schema::MatchType match_type = schema::MatchType::Contain,
    const std::vector<::flatbuffers::Offset<schema::AnnotationMatcher>> *annotations = nullptr) {
  auto annotations__ = annotations ? _fbb.CreateVector<::flatbuffers::Offset<schema::AnnotationMatcher>>(*annotations) : 0;
  return schema::CreateAnnotationsMatcher(
      _fbb,
      annotaion_count,
      match_type,
      annotations__);
}

struct ParameterMatcher FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ParameterMatcherBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PRAMETER_TYPE = 4,
    VT_ANNOTATIONS = 6
  };
  const schema::ClassMatcher *prameter_type() const {
    return GetPointer<const schema::ClassMatcher *>(VT_PRAMETER_TYPE);
  }
  const schema::AnnotationsMatcher *annotations() const {
    return GetPointer<const schema::AnnotationsMatcher *>(VT_ANNOTATIONS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_PRAMETER_TYPE) &&
           verifier.VerifyTable(prameter_type()) &&
           VerifyOffset(verifier, VT_ANNOTATIONS) &&
           verifier.VerifyTable(annotations()) &&
           verifier.EndTable();
  }
};

struct ParameterMatcherBuilder {
  typedef ParameterMatcher Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_prameter_type(::flatbuffers::Offset<schema::ClassMatcher> prameter_type) {
    fbb_.AddOffset(ParameterMatcher::VT_PRAMETER_TYPE, prameter_type);
  }
  void add_annotations(::flatbuffers::Offset<schema::AnnotationsMatcher> annotations) {
    fbb_.AddOffset(ParameterMatcher::VT_ANNOTATIONS, annotations);
  }
  explicit ParameterMatcherBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ParameterMatcher> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ParameterMatcher>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ParameterMatcher> CreateParameterMatcher(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<schema::ClassMatcher> prameter_type = 0,
    ::flatbuffers::Offset<schema::AnnotationsMatcher> annotations = 0) {
  ParameterMatcherBuilder builder_(_fbb);
  builder_.add_annotations(annotations);
  builder_.add_prameter_type(prameter_type);
  return builder_.Finish();
}

struct ParameterMatcher::Traits {
  using type = ParameterMatcher;
  static auto constexpr Create = CreateParameterMatcher;
};

struct ParametersMatcher FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ParametersMatcherBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PARAMETER_COUNT = 4,
    VT_MATCH_TYPE = 6,
    VT_PARAMETERS = 8
  };
  const schema::IntRange *parameter_count() const {
    return GetPointer<const schema::IntRange *>(VT_PARAMETER_COUNT);
  }
  schema::MatchType match_type() const {
    return static_cast<schema::MatchType>(GetField<int8_t>(VT_MATCH_TYPE, 0));
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<schema::ParameterMatcher>> *parameters() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<schema::ParameterMatcher>> *>(VT_PARAMETERS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_PARAMETER_COUNT) &&
           verifier.VerifyTable(parameter_count()) &&
           VerifyField<int8_t>(verifier, VT_MATCH_TYPE, 1) &&
           VerifyOffset(verifier, VT_PARAMETERS) &&
           verifier.VerifyVector(parameters()) &&
           verifier.VerifyVectorOfTables(parameters()) &&
           verifier.EndTable();
  }
};

struct ParametersMatcherBuilder {
  typedef ParametersMatcher Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_parameter_count(::flatbuffers::Offset<schema::IntRange> parameter_count) {
    fbb_.AddOffset(ParametersMatcher::VT_PARAMETER_COUNT, parameter_count);
  }
  void add_match_type(schema::MatchType match_type) {
    fbb_.AddElement<int8_t>(ParametersMatcher::VT_MATCH_TYPE, static_cast<int8_t>(match_type), 0);
  }
  void add_parameters(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<schema::ParameterMatcher>>> parameters) {
    fbb_.AddOffset(ParametersMatcher::VT_PARAMETERS, parameters);
  }
  explicit ParametersMatcherBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ParametersMatcher> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ParametersMatcher>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ParametersMatcher> CreateParametersMatcher(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<schema::IntRange> parameter_count = 0,
    schema::MatchType match_type = schema::MatchType::Contain,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<schema::ParameterMatcher>>> parameters = 0) {
  ParametersMatcherBuilder builder_(_fbb);
  builder_.add_parameters(parameters);
  builder_.add_parameter_count(parameter_count);
  builder_.add_match_type(match_type);
  return builder_.Finish();
}

struct ParametersMatcher::Traits {
  using type = ParametersMatcher;
  static auto constexpr Create = CreateParametersMatcher;
};

inline ::flatbuffers::Offset<ParametersMatcher> CreateParametersMatcherDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<schema::IntRange> parameter_count = 0,
    schema::MatchType match_type = schema::MatchType::Contain,
    const std::vector<::flatbuffers::Offset<schema::ParameterMatcher>> *parameters = nullptr) {
  auto parameters__ = parameters ? _fbb.CreateVector<::flatbuffers::Offset<schema::ParameterMatcher>>(*parameters) : 0;
  return schema::CreateParametersMatcher(
      _fbb,
      parameter_count,
      match_type,
      parameters__);
}

struct OpCodesMatcher FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef OpCodesMatcherBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_MATCH_TYPE = 4,
    VT_OP_CODES = 6
  };
  schema::OpCodeMatchType match_type() const {
    return static_cast<schema::OpCodeMatchType>(GetField<int8_t>(VT_MATCH_TYPE, 0));
  }
  const ::flatbuffers::Vector<uint8_t> *op_codes() const {
    return GetPointer<const ::flatbuffers::Vector<uint8_t> *>(VT_OP_CODES);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int8_t>(verifier, VT_MATCH_TYPE, 1) &&
           VerifyOffset(verifier, VT_OP_CODES) &&
           verifier.VerifyVector(op_codes()) &&
           verifier.EndTable();
  }
};

struct OpCodesMatcherBuilder {
  typedef OpCodesMatcher Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_match_type(schema::OpCodeMatchType match_type) {
    fbb_.AddElement<int8_t>(OpCodesMatcher::VT_MATCH_TYPE, static_cast<int8_t>(match_type), 0);
  }
  void add_op_codes(::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> op_codes) {
    fbb_.AddOffset(OpCodesMatcher::VT_OP_CODES, op_codes);
  }
  explicit OpCodesMatcherBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<OpCodesMatcher> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<OpCodesMatcher>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<OpCodesMatcher> CreateOpCodesMatcher(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    schema::OpCodeMatchType match_type = schema::OpCodeMatchType::Contains,
    ::flatbuffers::Offset<::flatbuffers::Vector<uint8_t>> op_codes = 0) {
  OpCodesMatcherBuilder builder_(_fbb);
  builder_.add_op_codes(op_codes);
  builder_.add_match_type(match_type);
  return builder_.Finish();
}

struct OpCodesMatcher::Traits {
  using type = OpCodesMatcher;
  static auto constexpr Create = CreateOpCodesMatcher;
};

inline ::flatbuffers::Offset<OpCodesMatcher> CreateOpCodesMatcherDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    schema::OpCodeMatchType match_type = schema::OpCodeMatchType::Contains,
    const std::vector<uint8_t> *op_codes = nullptr) {
  auto op_codes__ = op_codes ? _fbb.CreateVector<uint8_t>(*op_codes) : 0;
  return schema::CreateOpCodesMatcher(
      _fbb,
      match_type,
      op_codes__);
}

struct UsingFieldMatcher FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef UsingFieldMatcherBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_USING_TYPE = 4,
    VT_FIELD = 6
  };
  schema::UsingType using_type() const {
    return static_cast<schema::UsingType>(GetField<int8_t>(VT_USING_TYPE, 0));
  }
  const schema::FieldMatcher *field() const {
    return GetPointer<const schema::FieldMatcher *>(VT_FIELD);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int8_t>(verifier, VT_USING_TYPE, 1) &&
           VerifyOffset(verifier, VT_FIELD) &&
           verifier.VerifyTable(field()) &&
           verifier.EndTable();
  }
};

struct UsingFieldMatcherBuilder {
  typedef UsingFieldMatcher Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_using_type(schema::UsingType using_type) {
    fbb_.AddElement<int8_t>(UsingFieldMatcher::VT_USING_TYPE, static_cast<int8_t>(using_type), 0);
  }
  void add_field(::flatbuffers::Offset<schema::FieldMatcher> field) {
    fbb_.AddOffset(UsingFieldMatcher::VT_FIELD, field);
  }
  explicit UsingFieldMatcherBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<UsingFieldMatcher> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<UsingFieldMatcher>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<UsingFieldMatcher> CreateUsingFieldMatcher(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    schema::UsingType using_type = schema::UsingType::Any,
    ::flatbuffers::Offset<schema::FieldMatcher> field = 0) {
  UsingFieldMatcherBuilder builder_(_fbb);
  builder_.add_field(field);
  builder_.add_using_type(using_type);
  return builder_.Finish();
}

struct UsingFieldMatcher::Traits {
  using type = UsingFieldMatcher;
  static auto constexpr Create = CreateUsingFieldMatcher;
};

struct UsingNumberMatcher FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef UsingNumberMatcherBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_USING_TYPE = 4,
    VT_NUMBER_TYPE = 6,
    VT_NUMBER = 8
  };
  schema::UsingType using_type() const {
    return static_cast<schema::UsingType>(GetField<int8_t>(VT_USING_TYPE, 0));
  }
  schema::Number number_type() const {
    return static_cast<schema::Number>(GetField<uint8_t>(VT_NUMBER_TYPE, 0));
  }
  const void *number() const {
    return GetPointer<const void *>(VT_NUMBER);
  }
  template<typename T> const T *number_as() const;
  const schema::EncodeValueShort *number_as_EncodeValueShort() const {
    return number_type() == schema::Number::EncodeValueShort ? static_cast<const schema::EncodeValueShort *>(number()) : nullptr;
  }
  const schema::EncodeValueInt *number_as_EncodeValueInt() const {
    return number_type() == schema::Number::EncodeValueInt ? static_cast<const schema::EncodeValueInt *>(number()) : nullptr;
  }
  const schema::EncodeValueLong *number_as_EncodeValueLong() const {
    return number_type() == schema::Number::EncodeValueLong ? static_cast<const schema::EncodeValueLong *>(number()) : nullptr;
  }
  const schema::EncodeValueFloat *number_as_EncodeValueFloat() const {
    return number_type() == schema::Number::EncodeValueFloat ? static_cast<const schema::EncodeValueFloat *>(number()) : nullptr;
  }
  const schema::EncodeValueDouble *number_as_EncodeValueDouble() const {
    return number_type() == schema::Number::EncodeValueDouble ? static_cast<const schema::EncodeValueDouble *>(number()) : nullptr;
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int8_t>(verifier, VT_USING_TYPE, 1) &&
           VerifyField<uint8_t>(verifier, VT_NUMBER_TYPE, 1) &&
           VerifyOffset(verifier, VT_NUMBER) &&
           VerifyNumber(verifier, number(), number_type()) &&
           verifier.EndTable();
  }
};

template<> inline const schema::EncodeValueShort *UsingNumberMatcher::number_as<schema::EncodeValueShort>() const {
  return number_as_EncodeValueShort();
}

template<> inline const schema::EncodeValueInt *UsingNumberMatcher::number_as<schema::EncodeValueInt>() const {
  return number_as_EncodeValueInt();
}

template<> inline const schema::EncodeValueLong *UsingNumberMatcher::number_as<schema::EncodeValueLong>() const {
  return number_as_EncodeValueLong();
}

template<> inline const schema::EncodeValueFloat *UsingNumberMatcher::number_as<schema::EncodeValueFloat>() const {
  return number_as_EncodeValueFloat();
}

template<> inline const schema::EncodeValueDouble *UsingNumberMatcher::number_as<schema::EncodeValueDouble>() const {
  return number_as_EncodeValueDouble();
}

struct UsingNumberMatcherBuilder {
  typedef UsingNumberMatcher Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_using_type(schema::UsingType using_type) {
    fbb_.AddElement<int8_t>(UsingNumberMatcher::VT_USING_TYPE, static_cast<int8_t>(using_type), 0);
  }
  void add_number_type(schema::Number number_type) {
    fbb_.AddElement<uint8_t>(UsingNumberMatcher::VT_NUMBER_TYPE, static_cast<uint8_t>(number_type), 0);
  }
  void add_number(::flatbuffers::Offset<void> number) {
    fbb_.AddOffset(UsingNumberMatcher::VT_NUMBER, number);
  }
  explicit UsingNumberMatcherBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<UsingNumberMatcher> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<UsingNumberMatcher>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<UsingNumberMatcher> CreateUsingNumberMatcher(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    schema::UsingType using_type = schema::UsingType::Any,
    schema::Number number_type = schema::Number::NONE,
    ::flatbuffers::Offset<void> number = 0) {
  UsingNumberMatcherBuilder builder_(_fbb);
  builder_.add_number(number);
  builder_.add_number_type(number_type);
  builder_.add_using_type(using_type);
  return builder_.Finish();
}

struct UsingNumberMatcher::Traits {
  using type = UsingNumberMatcher;
  static auto constexpr Create = CreateUsingNumberMatcher;
};

struct MethodMatcher FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MethodMatcherBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_METHOD_NAME = 4,
    VT_ACCESS_FLAGS = 6,
    VT_DECLARING_CLASS = 8,
    VT_RETURN_TYPE = 10,
    VT_PARAMETERS = 12,
    VT_ANNOTATIONS = 14,
    VT_OP_CODES = 16,
    VT_USING_STRINGS = 18,
    VT_USING_FIELS = 20,
    VT_USING_NUMBERS = 22,
    VT_INVOKE_METHODS = 24,
    VT_CALL_METHODS = 26
  };
  const schema::StringMatcher *method_name() const {
    return GetPointer<const schema::StringMatcher *>(VT_METHOD_NAME);
  }
  const schema::AccessFlagsMatcher *access_flags() const {
    return GetPointer<const schema::AccessFlagsMatcher *>(VT_ACCESS_FLAGS);
  }
  const schema::ClassMatcher *declaring_class() const {
    return GetPointer<const schema::ClassMatcher *>(VT_DECLARING_CLASS);
  }
  const schema::ClassMatcher *return_type() const {
    return GetPointer<const schema::ClassMatcher *>(VT_RETURN_TYPE);
  }
  const schema::ParametersMatcher *parameters() const {
    return GetPointer<const schema::ParametersMatcher *>(VT_PARAMETERS);
  }
  const schema::AnnotationsMatcher *annotations() const {
    return GetPointer<const schema::AnnotationsMatcher *>(VT_ANNOTATIONS);
  }
  const schema::OpCodesMatcher *op_codes() const {
    return GetPointer<const schema::OpCodesMatcher *>(VT_OP_CODES);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<schema::StringMatcher>> *using_strings() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<schema::StringMatcher>> *>(VT_USING_STRINGS);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<schema::UsingFieldMatcher>> *using_fiels() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<schema::UsingFieldMatcher>> *>(VT_USING_FIELS);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<schema::UsingNumberMatcher>> *using_numbers() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<schema::UsingNumberMatcher>> *>(VT_USING_NUMBERS);
  }
  const schema::MethodsMatcher *invoke_methods() const {
    return GetPointer<const schema::MethodsMatcher *>(VT_INVOKE_METHODS);
  }
  const schema::MethodsMatcher *call_methods() const {
    return GetPointer<const schema::MethodsMatcher *>(VT_CALL_METHODS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_METHOD_NAME) &&
           verifier.VerifyTable(method_name()) &&
           VerifyOffset(verifier, VT_ACCESS_FLAGS) &&
           verifier.VerifyTable(access_flags()) &&
           VerifyOffset(verifier, VT_DECLARING_CLASS) &&
           verifier.VerifyTable(declaring_class()) &&
           VerifyOffset(verifier, VT_RETURN_TYPE) &&
           verifier.VerifyTable(return_type()) &&
           VerifyOffset(verifier, VT_PARAMETERS) &&
           verifier.VerifyTable(parameters()) &&
           VerifyOffset(verifier, VT_ANNOTATIONS) &&
           verifier.VerifyTable(annotations()) &&
           VerifyOffset(verifier, VT_OP_CODES) &&
           verifier.VerifyTable(op_codes()) &&
           VerifyOffset(verifier, VT_USING_STRINGS) &&
           verifier.VerifyVector(using_strings()) &&
           verifier.VerifyVectorOfTables(using_strings()) &&
           VerifyOffset(verifier, VT_USING_FIELS) &&
           verifier.VerifyVector(using_fiels()) &&
           verifier.VerifyVectorOfTables(using_fiels()) &&
           VerifyOffset(verifier, VT_USING_NUMBERS) &&
           verifier.VerifyVector(using_numbers()) &&
           verifier.VerifyVectorOfTables(using_numbers()) &&
           VerifyOffset(verifier, VT_INVOKE_METHODS) &&
           verifier.VerifyTable(invoke_methods()) &&
           VerifyOffset(verifier, VT_CALL_METHODS) &&
           verifier.VerifyTable(call_methods()) &&
           verifier.EndTable();
  }
};

struct MethodMatcherBuilder {
  typedef MethodMatcher Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_method_name(::flatbuffers::Offset<schema::StringMatcher> method_name) {
    fbb_.AddOffset(MethodMatcher::VT_METHOD_NAME, method_name);
  }
  void add_access_flags(::flatbuffers::Offset<schema::AccessFlagsMatcher> access_flags) {
    fbb_.AddOffset(MethodMatcher::VT_ACCESS_FLAGS, access_flags);
  }
  void add_declaring_class(::flatbuffers::Offset<schema::ClassMatcher> declaring_class) {
    fbb_.AddOffset(MethodMatcher::VT_DECLARING_CLASS, declaring_class);
  }
  void add_return_type(::flatbuffers::Offset<schema::ClassMatcher> return_type) {
    fbb_.AddOffset(MethodMatcher::VT_RETURN_TYPE, return_type);
  }
  void add_parameters(::flatbuffers::Offset<schema::ParametersMatcher> parameters) {
    fbb_.AddOffset(MethodMatcher::VT_PARAMETERS, parameters);
  }
  void add_annotations(::flatbuffers::Offset<schema::AnnotationsMatcher> annotations) {
    fbb_.AddOffset(MethodMatcher::VT_ANNOTATIONS, annotations);
  }
  void add_op_codes(::flatbuffers::Offset<schema::OpCodesMatcher> op_codes) {
    fbb_.AddOffset(MethodMatcher::VT_OP_CODES, op_codes);
  }
  void add_using_strings(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<schema::StringMatcher>>> using_strings) {
    fbb_.AddOffset(MethodMatcher::VT_USING_STRINGS, using_strings);
  }
  void add_using_fiels(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<schema::UsingFieldMatcher>>> using_fiels) {
    fbb_.AddOffset(MethodMatcher::VT_USING_FIELS, using_fiels);
  }
  void add_using_numbers(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<schema::UsingNumberMatcher>>> using_numbers) {
    fbb_.AddOffset(MethodMatcher::VT_USING_NUMBERS, using_numbers);
  }
  void add_invoke_methods(::flatbuffers::Offset<schema::MethodsMatcher> invoke_methods) {
    fbb_.AddOffset(MethodMatcher::VT_INVOKE_METHODS, invoke_methods);
  }
  void add_call_methods(::flatbuffers::Offset<schema::MethodsMatcher> call_methods) {
    fbb_.AddOffset(MethodMatcher::VT_CALL_METHODS, call_methods);
  }
  explicit MethodMatcherBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<MethodMatcher> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<MethodMatcher>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<MethodMatcher> CreateMethodMatcher(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<schema::StringMatcher> method_name = 0,
    ::flatbuffers::Offset<schema::AccessFlagsMatcher> access_flags = 0,
    ::flatbuffers::Offset<schema::ClassMatcher> declaring_class = 0,
    ::flatbuffers::Offset<schema::ClassMatcher> return_type = 0,
    ::flatbuffers::Offset<schema::ParametersMatcher> parameters = 0,
    ::flatbuffers::Offset<schema::AnnotationsMatcher> annotations = 0,
    ::flatbuffers::Offset<schema::OpCodesMatcher> op_codes = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<schema::StringMatcher>>> using_strings = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<schema::UsingFieldMatcher>>> using_fiels = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<schema::UsingNumberMatcher>>> using_numbers = 0,
    ::flatbuffers::Offset<schema::MethodsMatcher> invoke_methods = 0,
    ::flatbuffers::Offset<schema::MethodsMatcher> call_methods = 0) {
  MethodMatcherBuilder builder_(_fbb);
  builder_.add_call_methods(call_methods);
  builder_.add_invoke_methods(invoke_methods);
  builder_.add_using_numbers(using_numbers);
  builder_.add_using_fiels(using_fiels);
  builder_.add_using_strings(using_strings);
  builder_.add_op_codes(op_codes);
  builder_.add_annotations(annotations);
  builder_.add_parameters(parameters);
  builder_.add_return_type(return_type);
  builder_.add_declaring_class(declaring_class);
  builder_.add_access_flags(access_flags);
  builder_.add_method_name(method_name);
  return builder_.Finish();
}

struct MethodMatcher::Traits {
  using type = MethodMatcher;
  static auto constexpr Create = CreateMethodMatcher;
};

inline ::flatbuffers::Offset<MethodMatcher> CreateMethodMatcherDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<schema::StringMatcher> method_name = 0,
    ::flatbuffers::Offset<schema::AccessFlagsMatcher> access_flags = 0,
    ::flatbuffers::Offset<schema::ClassMatcher> declaring_class = 0,
    ::flatbuffers::Offset<schema::ClassMatcher> return_type = 0,
    ::flatbuffers::Offset<schema::ParametersMatcher> parameters = 0,
    ::flatbuffers::Offset<schema::AnnotationsMatcher> annotations = 0,
    ::flatbuffers::Offset<schema::OpCodesMatcher> op_codes = 0,
    const std::vector<::flatbuffers::Offset<schema::StringMatcher>> *using_strings = nullptr,
    const std::vector<::flatbuffers::Offset<schema::UsingFieldMatcher>> *using_fiels = nullptr,
    const std::vector<::flatbuffers::Offset<schema::UsingNumberMatcher>> *using_numbers = nullptr,
    ::flatbuffers::Offset<schema::MethodsMatcher> invoke_methods = 0,
    ::flatbuffers::Offset<schema::MethodsMatcher> call_methods = 0) {
  auto using_strings__ = using_strings ? _fbb.CreateVector<::flatbuffers::Offset<schema::StringMatcher>>(*using_strings) : 0;
  auto using_fiels__ = using_fiels ? _fbb.CreateVector<::flatbuffers::Offset<schema::UsingFieldMatcher>>(*using_fiels) : 0;
  auto using_numbers__ = using_numbers ? _fbb.CreateVector<::flatbuffers::Offset<schema::UsingNumberMatcher>>(*using_numbers) : 0;
  return schema::CreateMethodMatcher(
      _fbb,
      method_name,
      access_flags,
      declaring_class,
      return_type,
      parameters,
      annotations,
      op_codes,
      using_strings__,
      using_fiels__,
      using_numbers__,
      invoke_methods,
      call_methods);
}

struct MethodsMatcher FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef MethodsMatcherBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_METHOD_COUNT = 4,
    VT_MATCH_TYPE = 6,
    VT_METHODS = 8
  };
  const schema::IntRange *method_count() const {
    return GetPointer<const schema::IntRange *>(VT_METHOD_COUNT);
  }
  schema::MatchType match_type() const {
    return static_cast<schema::MatchType>(GetField<int8_t>(VT_MATCH_TYPE, 0));
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<schema::MethodMatcher>> *methods() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<schema::MethodMatcher>> *>(VT_METHODS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_METHOD_COUNT) &&
           verifier.VerifyTable(method_count()) &&
           VerifyField<int8_t>(verifier, VT_MATCH_TYPE, 1) &&
           VerifyOffset(verifier, VT_METHODS) &&
           verifier.VerifyVector(methods()) &&
           verifier.VerifyVectorOfTables(methods()) &&
           verifier.EndTable();
  }
};

struct MethodsMatcherBuilder {
  typedef MethodsMatcher Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_method_count(::flatbuffers::Offset<schema::IntRange> method_count) {
    fbb_.AddOffset(MethodsMatcher::VT_METHOD_COUNT, method_count);
  }
  void add_match_type(schema::MatchType match_type) {
    fbb_.AddElement<int8_t>(MethodsMatcher::VT_MATCH_TYPE, static_cast<int8_t>(match_type), 0);
  }
  void add_methods(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<schema::MethodMatcher>>> methods) {
    fbb_.AddOffset(MethodsMatcher::VT_METHODS, methods);
  }
  explicit MethodsMatcherBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<MethodsMatcher> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<MethodsMatcher>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<MethodsMatcher> CreateMethodsMatcher(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<schema::IntRange> method_count = 0,
    schema::MatchType match_type = schema::MatchType::Contain,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<schema::MethodMatcher>>> methods = 0) {
  MethodsMatcherBuilder builder_(_fbb);
  builder_.add_methods(methods);
  builder_.add_method_count(method_count);
  builder_.add_match_type(match_type);
  return builder_.Finish();
}

struct MethodsMatcher::Traits {
  using type = MethodsMatcher;
  static auto constexpr Create = CreateMethodsMatcher;
};

inline ::flatbuffers::Offset<MethodsMatcher> CreateMethodsMatcherDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<schema::IntRange> method_count = 0,
    schema::MatchType match_type = schema::MatchType::Contain,
    const std::vector<::flatbuffers::Offset<schema::MethodMatcher>> *methods = nullptr) {
  auto methods__ = methods ? _fbb.CreateVector<::flatbuffers::Offset<schema::MethodMatcher>>(*methods) : 0;
  return schema::CreateMethodsMatcher(
      _fbb,
      method_count,
      match_type,
      methods__);
}

struct InterfacesMatcher FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef InterfacesMatcherBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_INTERFACE_COUNT = 4,
    VT_MATCH_TYPE = 6,
    VT_INTERFACES = 8
  };
  const schema::IntRange *interface_count() const {
    return GetPointer<const schema::IntRange *>(VT_INTERFACE_COUNT);
  }
  schema::MatchType match_type() const {
    return static_cast<schema::MatchType>(GetField<int8_t>(VT_MATCH_TYPE, 0));
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<schema::ClassMatcher>> *interfaces() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<schema::ClassMatcher>> *>(VT_INTERFACES);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_INTERFACE_COUNT) &&
           verifier.VerifyTable(interface_count()) &&
           VerifyField<int8_t>(verifier, VT_MATCH_TYPE, 1) &&
           VerifyOffset(verifier, VT_INTERFACES) &&
           verifier.VerifyVector(interfaces()) &&
           verifier.VerifyVectorOfTables(interfaces()) &&
           verifier.EndTable();
  }
};

struct InterfacesMatcherBuilder {
  typedef InterfacesMatcher Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_interface_count(::flatbuffers::Offset<schema::IntRange> interface_count) {
    fbb_.AddOffset(InterfacesMatcher::VT_INTERFACE_COUNT, interface_count);
  }
  void add_match_type(schema::MatchType match_type) {
    fbb_.AddElement<int8_t>(InterfacesMatcher::VT_MATCH_TYPE, static_cast<int8_t>(match_type), 0);
  }
  void add_interfaces(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<schema::ClassMatcher>>> interfaces) {
    fbb_.AddOffset(InterfacesMatcher::VT_INTERFACES, interfaces);
  }
  explicit InterfacesMatcherBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<InterfacesMatcher> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<InterfacesMatcher>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<InterfacesMatcher> CreateInterfacesMatcher(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<schema::IntRange> interface_count = 0,
    schema::MatchType match_type = schema::MatchType::Contain,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<schema::ClassMatcher>>> interfaces = 0) {
  InterfacesMatcherBuilder builder_(_fbb);
  builder_.add_interfaces(interfaces);
  builder_.add_interface_count(interface_count);
  builder_.add_match_type(match_type);
  return builder_.Finish();
}

struct InterfacesMatcher::Traits {
  using type = InterfacesMatcher;
  static auto constexpr Create = CreateInterfacesMatcher;
};

inline ::flatbuffers::Offset<InterfacesMatcher> CreateInterfacesMatcherDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<schema::IntRange> interface_count = 0,
    schema::MatchType match_type = schema::MatchType::Contain,
    const std::vector<::flatbuffers::Offset<schema::ClassMatcher>> *interfaces = nullptr) {
  auto interfaces__ = interfaces ? _fbb.CreateVector<::flatbuffers::Offset<schema::ClassMatcher>>(*interfaces) : 0;
  return schema::CreateInterfacesMatcher(
      _fbb,
      interface_count,
      match_type,
      interfaces__);
}

struct FieldMatcher FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef FieldMatcherBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_ACCESS_FLAGS = 4,
    VT_DECLARING_CLASS = 6,
    VT_TYPE_CLASS = 8,
    VT_ANNOTATIONS = 10,
    VT_GET_METHODS = 12,
    VT_PUT_METHODS = 14
  };
  const schema::AccessFlagsMatcher *access_flags() const {
    return GetPointer<const schema::AccessFlagsMatcher *>(VT_ACCESS_FLAGS);
  }
  const schema::ClassMatcher *declaring_class() const {
    return GetPointer<const schema::ClassMatcher *>(VT_DECLARING_CLASS);
  }
  const schema::ClassMatcher *type_class() const {
    return GetPointer<const schema::ClassMatcher *>(VT_TYPE_CLASS);
  }
  const schema::AnnotationsMatcher *annotations() const {
    return GetPointer<const schema::AnnotationsMatcher *>(VT_ANNOTATIONS);
  }
  const schema::MethodsMatcher *get_methods() const {
    return GetPointer<const schema::MethodsMatcher *>(VT_GET_METHODS);
  }
  const schema::MethodsMatcher *put_methods() const {
    return GetPointer<const schema::MethodsMatcher *>(VT_PUT_METHODS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_ACCESS_FLAGS) &&
           verifier.VerifyTable(access_flags()) &&
           VerifyOffset(verifier, VT_DECLARING_CLASS) &&
           verifier.VerifyTable(declaring_class()) &&
           VerifyOffset(verifier, VT_TYPE_CLASS) &&
           verifier.VerifyTable(type_class()) &&
           VerifyOffset(verifier, VT_ANNOTATIONS) &&
           verifier.VerifyTable(annotations()) &&
           VerifyOffset(verifier, VT_GET_METHODS) &&
           verifier.VerifyTable(get_methods()) &&
           VerifyOffset(verifier, VT_PUT_METHODS) &&
           verifier.VerifyTable(put_methods()) &&
           verifier.EndTable();
  }
};

struct FieldMatcherBuilder {
  typedef FieldMatcher Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_access_flags(::flatbuffers::Offset<schema::AccessFlagsMatcher> access_flags) {
    fbb_.AddOffset(FieldMatcher::VT_ACCESS_FLAGS, access_flags);
  }
  void add_declaring_class(::flatbuffers::Offset<schema::ClassMatcher> declaring_class) {
    fbb_.AddOffset(FieldMatcher::VT_DECLARING_CLASS, declaring_class);
  }
  void add_type_class(::flatbuffers::Offset<schema::ClassMatcher> type_class) {
    fbb_.AddOffset(FieldMatcher::VT_TYPE_CLASS, type_class);
  }
  void add_annotations(::flatbuffers::Offset<schema::AnnotationsMatcher> annotations) {
    fbb_.AddOffset(FieldMatcher::VT_ANNOTATIONS, annotations);
  }
  void add_get_methods(::flatbuffers::Offset<schema::MethodsMatcher> get_methods) {
    fbb_.AddOffset(FieldMatcher::VT_GET_METHODS, get_methods);
  }
  void add_put_methods(::flatbuffers::Offset<schema::MethodsMatcher> put_methods) {
    fbb_.AddOffset(FieldMatcher::VT_PUT_METHODS, put_methods);
  }
  explicit FieldMatcherBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<FieldMatcher> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<FieldMatcher>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<FieldMatcher> CreateFieldMatcher(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<schema::AccessFlagsMatcher> access_flags = 0,
    ::flatbuffers::Offset<schema::ClassMatcher> declaring_class = 0,
    ::flatbuffers::Offset<schema::ClassMatcher> type_class = 0,
    ::flatbuffers::Offset<schema::AnnotationsMatcher> annotations = 0,
    ::flatbuffers::Offset<schema::MethodsMatcher> get_methods = 0,
    ::flatbuffers::Offset<schema::MethodsMatcher> put_methods = 0) {
  FieldMatcherBuilder builder_(_fbb);
  builder_.add_put_methods(put_methods);
  builder_.add_get_methods(get_methods);
  builder_.add_annotations(annotations);
  builder_.add_type_class(type_class);
  builder_.add_declaring_class(declaring_class);
  builder_.add_access_flags(access_flags);
  return builder_.Finish();
}

struct FieldMatcher::Traits {
  using type = FieldMatcher;
  static auto constexpr Create = CreateFieldMatcher;
};

struct FieldsMatcher FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef FieldsMatcherBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_FIELD_COUNT = 4,
    VT_MATCH_TYPE = 6,
    VT_FIELDS = 8
  };
  const schema::IntRange *field_count() const {
    return GetPointer<const schema::IntRange *>(VT_FIELD_COUNT);
  }
  schema::MatchType match_type() const {
    return static_cast<schema::MatchType>(GetField<int8_t>(VT_MATCH_TYPE, 0));
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<schema::FieldMatcher>> *fields() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<schema::FieldMatcher>> *>(VT_FIELDS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_FIELD_COUNT) &&
           verifier.VerifyTable(field_count()) &&
           VerifyField<int8_t>(verifier, VT_MATCH_TYPE, 1) &&
           VerifyOffset(verifier, VT_FIELDS) &&
           verifier.VerifyVector(fields()) &&
           verifier.VerifyVectorOfTables(fields()) &&
           verifier.EndTable();
  }
};

struct FieldsMatcherBuilder {
  typedef FieldsMatcher Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_field_count(::flatbuffers::Offset<schema::IntRange> field_count) {
    fbb_.AddOffset(FieldsMatcher::VT_FIELD_COUNT, field_count);
  }
  void add_match_type(schema::MatchType match_type) {
    fbb_.AddElement<int8_t>(FieldsMatcher::VT_MATCH_TYPE, static_cast<int8_t>(match_type), 0);
  }
  void add_fields(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<schema::FieldMatcher>>> fields) {
    fbb_.AddOffset(FieldsMatcher::VT_FIELDS, fields);
  }
  explicit FieldsMatcherBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<FieldsMatcher> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<FieldsMatcher>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<FieldsMatcher> CreateFieldsMatcher(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<schema::IntRange> field_count = 0,
    schema::MatchType match_type = schema::MatchType::Contain,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<schema::FieldMatcher>>> fields = 0) {
  FieldsMatcherBuilder builder_(_fbb);
  builder_.add_fields(fields);
  builder_.add_field_count(field_count);
  builder_.add_match_type(match_type);
  return builder_.Finish();
}

struct FieldsMatcher::Traits {
  using type = FieldsMatcher;
  static auto constexpr Create = CreateFieldsMatcher;
};

inline ::flatbuffers::Offset<FieldsMatcher> CreateFieldsMatcherDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<schema::IntRange> field_count = 0,
    schema::MatchType match_type = schema::MatchType::Contain,
    const std::vector<::flatbuffers::Offset<schema::FieldMatcher>> *fields = nullptr) {
  auto fields__ = fields ? _fbb.CreateVector<::flatbuffers::Offset<schema::FieldMatcher>>(*fields) : 0;
  return schema::CreateFieldsMatcher(
      _fbb,
      field_count,
      match_type,
      fields__);
}

struct ClassMatcher FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef ClassMatcherBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_PACKAGE_NAME = 4,
    VT_SMALI_SOURCE = 6,
    VT_SIMPLE_NAME = 8,
    VT_ACCESS_FLAGS = 10,
    VT_SUPER_CLASS = 12,
    VT_INTERFACES = 14,
    VT_ANNOTATIONS = 16,
    VT_FIELDS = 18,
    VT_METHODS = 20,
    VT_USING_STRINGS = 22
  };
  const schema::StringMatcher *package_name() const {
    return GetPointer<const schema::StringMatcher *>(VT_PACKAGE_NAME);
  }
  const schema::StringMatcher *smali_source() const {
    return GetPointer<const schema::StringMatcher *>(VT_SMALI_SOURCE);
  }
  const schema::StringMatcher *simple_name() const {
    return GetPointer<const schema::StringMatcher *>(VT_SIMPLE_NAME);
  }
  const schema::AccessFlagsMatcher *access_flags() const {
    return GetPointer<const schema::AccessFlagsMatcher *>(VT_ACCESS_FLAGS);
  }
  const schema::ClassMatcher *super_class() const {
    return GetPointer<const schema::ClassMatcher *>(VT_SUPER_CLASS);
  }
  const schema::InterfacesMatcher *interfaces() const {
    return GetPointer<const schema::InterfacesMatcher *>(VT_INTERFACES);
  }
  const schema::AnnotationsMatcher *annotations() const {
    return GetPointer<const schema::AnnotationsMatcher *>(VT_ANNOTATIONS);
  }
  const schema::FieldsMatcher *fields() const {
    return GetPointer<const schema::FieldsMatcher *>(VT_FIELDS);
  }
  const schema::MethodsMatcher *methods() const {
    return GetPointer<const schema::MethodsMatcher *>(VT_METHODS);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<schema::StringMatcher>> *using_strings() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<schema::StringMatcher>> *>(VT_USING_STRINGS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_PACKAGE_NAME) &&
           verifier.VerifyTable(package_name()) &&
           VerifyOffset(verifier, VT_SMALI_SOURCE) &&
           verifier.VerifyTable(smali_source()) &&
           VerifyOffset(verifier, VT_SIMPLE_NAME) &&
           verifier.VerifyTable(simple_name()) &&
           VerifyOffset(verifier, VT_ACCESS_FLAGS) &&
           verifier.VerifyTable(access_flags()) &&
           VerifyOffset(verifier, VT_SUPER_CLASS) &&
           verifier.VerifyTable(super_class()) &&
           VerifyOffset(verifier, VT_INTERFACES) &&
           verifier.VerifyTable(interfaces()) &&
           VerifyOffset(verifier, VT_ANNOTATIONS) &&
           verifier.VerifyTable(annotations()) &&
           VerifyOffset(verifier, VT_FIELDS) &&
           verifier.VerifyTable(fields()) &&
           VerifyOffset(verifier, VT_METHODS) &&
           verifier.VerifyTable(methods()) &&
           VerifyOffset(verifier, VT_USING_STRINGS) &&
           verifier.VerifyVector(using_strings()) &&
           verifier.VerifyVectorOfTables(using_strings()) &&
           verifier.EndTable();
  }
};

struct ClassMatcherBuilder {
  typedef ClassMatcher Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_package_name(::flatbuffers::Offset<schema::StringMatcher> package_name) {
    fbb_.AddOffset(ClassMatcher::VT_PACKAGE_NAME, package_name);
  }
  void add_smali_source(::flatbuffers::Offset<schema::StringMatcher> smali_source) {
    fbb_.AddOffset(ClassMatcher::VT_SMALI_SOURCE, smali_source);
  }
  void add_simple_name(::flatbuffers::Offset<schema::StringMatcher> simple_name) {
    fbb_.AddOffset(ClassMatcher::VT_SIMPLE_NAME, simple_name);
  }
  void add_access_flags(::flatbuffers::Offset<schema::AccessFlagsMatcher> access_flags) {
    fbb_.AddOffset(ClassMatcher::VT_ACCESS_FLAGS, access_flags);
  }
  void add_super_class(::flatbuffers::Offset<schema::ClassMatcher> super_class) {
    fbb_.AddOffset(ClassMatcher::VT_SUPER_CLASS, super_class);
  }
  void add_interfaces(::flatbuffers::Offset<schema::InterfacesMatcher> interfaces) {
    fbb_.AddOffset(ClassMatcher::VT_INTERFACES, interfaces);
  }
  void add_annotations(::flatbuffers::Offset<schema::AnnotationsMatcher> annotations) {
    fbb_.AddOffset(ClassMatcher::VT_ANNOTATIONS, annotations);
  }
  void add_fields(::flatbuffers::Offset<schema::FieldsMatcher> fields) {
    fbb_.AddOffset(ClassMatcher::VT_FIELDS, fields);
  }
  void add_methods(::flatbuffers::Offset<schema::MethodsMatcher> methods) {
    fbb_.AddOffset(ClassMatcher::VT_METHODS, methods);
  }
  void add_using_strings(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<schema::StringMatcher>>> using_strings) {
    fbb_.AddOffset(ClassMatcher::VT_USING_STRINGS, using_strings);
  }
  explicit ClassMatcherBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<ClassMatcher> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<ClassMatcher>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<ClassMatcher> CreateClassMatcher(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<schema::StringMatcher> package_name = 0,
    ::flatbuffers::Offset<schema::StringMatcher> smali_source = 0,
    ::flatbuffers::Offset<schema::StringMatcher> simple_name = 0,
    ::flatbuffers::Offset<schema::AccessFlagsMatcher> access_flags = 0,
    ::flatbuffers::Offset<schema::ClassMatcher> super_class = 0,
    ::flatbuffers::Offset<schema::InterfacesMatcher> interfaces = 0,
    ::flatbuffers::Offset<schema::AnnotationsMatcher> annotations = 0,
    ::flatbuffers::Offset<schema::FieldsMatcher> fields = 0,
    ::flatbuffers::Offset<schema::MethodsMatcher> methods = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<schema::StringMatcher>>> using_strings = 0) {
  ClassMatcherBuilder builder_(_fbb);
  builder_.add_using_strings(using_strings);
  builder_.add_methods(methods);
  builder_.add_fields(fields);
  builder_.add_annotations(annotations);
  builder_.add_interfaces(interfaces);
  builder_.add_super_class(super_class);
  builder_.add_access_flags(access_flags);
  builder_.add_simple_name(simple_name);
  builder_.add_smali_source(smali_source);
  builder_.add_package_name(package_name);
  return builder_.Finish();
}

struct ClassMatcher::Traits {
  using type = ClassMatcher;
  static auto constexpr Create = CreateClassMatcher;
};

inline ::flatbuffers::Offset<ClassMatcher> CreateClassMatcherDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<schema::StringMatcher> package_name = 0,
    ::flatbuffers::Offset<schema::StringMatcher> smali_source = 0,
    ::flatbuffers::Offset<schema::StringMatcher> simple_name = 0,
    ::flatbuffers::Offset<schema::AccessFlagsMatcher> access_flags = 0,
    ::flatbuffers::Offset<schema::ClassMatcher> super_class = 0,
    ::flatbuffers::Offset<schema::InterfacesMatcher> interfaces = 0,
    ::flatbuffers::Offset<schema::AnnotationsMatcher> annotations = 0,
    ::flatbuffers::Offset<schema::FieldsMatcher> fields = 0,
    ::flatbuffers::Offset<schema::MethodsMatcher> methods = 0,
    const std::vector<::flatbuffers::Offset<schema::StringMatcher>> *using_strings = nullptr) {
  auto using_strings__ = using_strings ? _fbb.CreateVector<::flatbuffers::Offset<schema::StringMatcher>>(*using_strings) : 0;
  return schema::CreateClassMatcher(
      _fbb,
      package_name,
      smali_source,
      simple_name,
      access_flags,
      super_class,
      interfaces,
      annotations,
      fields,
      methods,
      using_strings__);
}

struct BatchUsingStringsMatcher FLATBUFFERS_FINAL_CLASS : private ::flatbuffers::Table {
  typedef BatchUsingStringsMatcherBuilder Builder;
  struct Traits;
  enum FlatBuffersVTableOffset FLATBUFFERS_VTABLE_UNDERLYING_TYPE {
    VT_UNION_ID = 4,
    VT_USING_STRINGS = 6
  };
  const ::flatbuffers::String *union_id() const {
    return GetPointer<const ::flatbuffers::String *>(VT_UNION_ID);
  }
  const ::flatbuffers::Vector<::flatbuffers::Offset<schema::StringMatcher>> *using_strings() const {
    return GetPointer<const ::flatbuffers::Vector<::flatbuffers::Offset<schema::StringMatcher>> *>(VT_USING_STRINGS);
  }
  bool Verify(::flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_UNION_ID) &&
           verifier.VerifyString(union_id()) &&
           VerifyOffset(verifier, VT_USING_STRINGS) &&
           verifier.VerifyVector(using_strings()) &&
           verifier.VerifyVectorOfTables(using_strings()) &&
           verifier.EndTable();
  }
};

struct BatchUsingStringsMatcherBuilder {
  typedef BatchUsingStringsMatcher Table;
  ::flatbuffers::FlatBufferBuilder &fbb_;
  ::flatbuffers::uoffset_t start_;
  void add_union_id(::flatbuffers::Offset<::flatbuffers::String> union_id) {
    fbb_.AddOffset(BatchUsingStringsMatcher::VT_UNION_ID, union_id);
  }
  void add_using_strings(::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<schema::StringMatcher>>> using_strings) {
    fbb_.AddOffset(BatchUsingStringsMatcher::VT_USING_STRINGS, using_strings);
  }
  explicit BatchUsingStringsMatcherBuilder(::flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  ::flatbuffers::Offset<BatchUsingStringsMatcher> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = ::flatbuffers::Offset<BatchUsingStringsMatcher>(end);
    return o;
  }
};

inline ::flatbuffers::Offset<BatchUsingStringsMatcher> CreateBatchUsingStringsMatcher(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    ::flatbuffers::Offset<::flatbuffers::String> union_id = 0,
    ::flatbuffers::Offset<::flatbuffers::Vector<::flatbuffers::Offset<schema::StringMatcher>>> using_strings = 0) {
  BatchUsingStringsMatcherBuilder builder_(_fbb);
  builder_.add_using_strings(using_strings);
  builder_.add_union_id(union_id);
  return builder_.Finish();
}

struct BatchUsingStringsMatcher::Traits {
  using type = BatchUsingStringsMatcher;
  static auto constexpr Create = CreateBatchUsingStringsMatcher;
};

inline ::flatbuffers::Offset<BatchUsingStringsMatcher> CreateBatchUsingStringsMatcherDirect(
    ::flatbuffers::FlatBufferBuilder &_fbb,
    const char *union_id = nullptr,
    const std::vector<::flatbuffers::Offset<schema::StringMatcher>> *using_strings = nullptr) {
  auto union_id__ = union_id ? _fbb.CreateString(union_id) : 0;
  auto using_strings__ = using_strings ? _fbb.CreateVector<::flatbuffers::Offset<schema::StringMatcher>>(*using_strings) : 0;
  return schema::CreateBatchUsingStringsMatcher(
      _fbb,
      union_id__,
      using_strings__);
}

inline bool VerifyAnnotationElementValueMatcher(::flatbuffers::Verifier &verifier, const void *obj, AnnotationElementValueMatcher type) {
  switch (type) {
    case AnnotationElementValueMatcher::NONE: {
      return true;
    }
    case AnnotationElementValueMatcher::EncodeValueBoolean: {
      auto ptr = reinterpret_cast<const schema::EncodeValueBoolean *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case AnnotationElementValueMatcher::EncodeValueByte: {
      auto ptr = reinterpret_cast<const schema::EncodeValueByte *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case AnnotationElementValueMatcher::EncodeValueShort: {
      auto ptr = reinterpret_cast<const schema::EncodeValueShort *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case AnnotationElementValueMatcher::EncodeValueChar: {
      auto ptr = reinterpret_cast<const schema::EncodeValueChar *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case AnnotationElementValueMatcher::EncodeValueInt: {
      auto ptr = reinterpret_cast<const schema::EncodeValueInt *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case AnnotationElementValueMatcher::EncodeValueLong: {
      auto ptr = reinterpret_cast<const schema::EncodeValueLong *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case AnnotationElementValueMatcher::EncodeValueFloat: {
      auto ptr = reinterpret_cast<const schema::EncodeValueFloat *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case AnnotationElementValueMatcher::EncodeValueDouble: {
      auto ptr = reinterpret_cast<const schema::EncodeValueDouble *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case AnnotationElementValueMatcher::StringMatcher: {
      auto ptr = reinterpret_cast<const schema::StringMatcher *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case AnnotationElementValueMatcher::ClassMatcher: {
      auto ptr = reinterpret_cast<const schema::ClassMatcher *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case AnnotationElementValueMatcher::AnnotationElementsMatcher: {
      auto ptr = reinterpret_cast<const schema::AnnotationElementsMatcher *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case AnnotationElementValueMatcher::AnnotationMatcher: {
      auto ptr = reinterpret_cast<const schema::AnnotationMatcher *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

inline bool VerifyAnnotationElementValueMatcherVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<AnnotationElementValueMatcher> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyAnnotationElementValueMatcher(
        verifier,  values->Get(i), types->GetEnum<AnnotationElementValueMatcher>(i))) {
      return false;
    }
  }
  return true;
}

inline bool VerifyNumber(::flatbuffers::Verifier &verifier, const void *obj, Number type) {
  switch (type) {
    case Number::NONE: {
      return true;
    }
    case Number::EncodeValueShort: {
      auto ptr = reinterpret_cast<const schema::EncodeValueShort *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Number::EncodeValueInt: {
      auto ptr = reinterpret_cast<const schema::EncodeValueInt *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Number::EncodeValueLong: {
      auto ptr = reinterpret_cast<const schema::EncodeValueLong *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Number::EncodeValueFloat: {
      auto ptr = reinterpret_cast<const schema::EncodeValueFloat *>(obj);
      return verifier.VerifyTable(ptr);
    }
    case Number::EncodeValueDouble: {
      auto ptr = reinterpret_cast<const schema::EncodeValueDouble *>(obj);
      return verifier.VerifyTable(ptr);
    }
    default: return true;
  }
}

inline bool VerifyNumberVector(::flatbuffers::Verifier &verifier, const ::flatbuffers::Vector<::flatbuffers::Offset<void>> *values, const ::flatbuffers::Vector<Number> *types) {
  if (!values || !types) return !values && !types;
  if (values->size() != types->size()) return false;
  for (::flatbuffers::uoffset_t i = 0; i < values->size(); ++i) {
    if (!VerifyNumber(
        verifier,  values->Get(i), types->GetEnum<Number>(i))) {
      return false;
    }
  }
  return true;
}

}  // namespace schema

#endif  // FLATBUFFERS_GENERATED_MATCHERS_SCHEMA_H_
