// automatically generated by the FlatBuffers compiler, do not modify

package org.luckypray.dexkit.schema

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class OptionalAnnotationEncodeValueMatcher : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : OptionalAnnotationEncodeValueMatcher {
        __init(_i, _bb)
        return this
    }
    val valueType : UByte
        get() {
            val o = __offset(4)
            return if(o != 0) bb.get(o + bb_pos).toUByte() else 0u
        }
    fun value(obj: Table) : Table? {
        val o = __offset(6); return if (o != 0) __union(obj, o + bb_pos) else null
    }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_23_5_26()
        fun getRootAsOptionalAnnotationEncodeValueMatcher(_bb: ByteBuffer): OptionalAnnotationEncodeValueMatcher = getRootAsOptionalAnnotationEncodeValueMatcher(_bb, OptionalAnnotationEncodeValueMatcher())
        fun getRootAsOptionalAnnotationEncodeValueMatcher(_bb: ByteBuffer, obj: OptionalAnnotationEncodeValueMatcher): OptionalAnnotationEncodeValueMatcher {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createOptionalAnnotationEncodeValueMatcher(builder: FlatBufferBuilder, valueType: UByte, valueOffset: Int) : Int {
            builder.startTable(2)
            addValue(builder, valueOffset)
            addValueType(builder, valueType)
            return endOptionalAnnotationEncodeValueMatcher(builder)
        }
        fun startOptionalAnnotationEncodeValueMatcher(builder: FlatBufferBuilder) = builder.startTable(2)
        fun addValueType(builder: FlatBufferBuilder, valueType: UByte) = builder.addByte(0, valueType.toByte(), 0)
        fun addValue(builder: FlatBufferBuilder, value: Int) = builder.addOffset(1, value, 0)
        fun endOptionalAnnotationEncodeValueMatcher(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
