// automatically generated by the FlatBuffers compiler, do not modify

package org.luckypray.dexkit.schema

@Suppress("unused")
internal class `-AnnotationEncodeValue` private constructor() {
    companion object {
        const val NONE: UByte = 0u
        const val EncodeValueByte: UByte = 1u
        const val EncodeValueShort: UByte = 2u
        const val EncodeValueChar: UByte = 3u
        const val EncodeValueInt: UByte = 4u
        const val EncodeValueLong: UByte = 5u
        const val EncodeValueFloat: UByte = 6u
        const val EncodeValueDouble: UByte = 7u
        const val EncodeValueString: UByte = 8u
        const val ClassMeta: UByte = 9u
        const val FieldMeta: UByte = 10u
        const val AnnotationEncodeArray: UByte = 11u
        const val AnnotationMeta: UByte = 12u
        const val EncodeValueBoolean: UByte = 13u
    }
}