// automatically generated by the FlatBuffers compiler, do not modify

package org.luckypray.dexkit.schema

@Suppress("unused")
internal class `-AnnotationEncodeValueType` private constructor() {
    companion object {
        const val ByteValue: Byte = 0
        const val ShortValue: Byte = 1
        const val CharValue: Byte = 2
        const val IntValue: Byte = 3
        const val LongValue: Byte = 4
        const val FloatValue: Byte = 5
        const val DoubleValue: Byte = 6
        const val StringValue: Byte = 7
        const val TypeValue: Byte = 8
        const val EnumValue: Byte = 9
        const val ArrayValue: Byte = 10
        const val AnnotationValue: Byte = 11
        const val BoolValue: Byte = 12
    }
}