// automatically generated by the FlatBuffers compiler, do not modify

package org.luckypray.dexkit.schema

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
class EncodeValueInt : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : EncodeValueInt {
        __init(_i, _bb)
        return this
    }
    val value : Int
        get() {
            val o = __offset(4)
            return if(o != 0) bb.getInt(o + bb_pos) else 0
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_23_5_26()
        fun getRootAsEncodeValueInt(_bb: ByteBuffer): EncodeValueInt = getRootAsEncodeValueInt(_bb, EncodeValueInt())
        fun getRootAsEncodeValueInt(_bb: ByteBuffer, obj: EncodeValueInt): EncodeValueInt {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createEncodeValueInt(builder: FlatBufferBuilder, value: Int) : Int {
            builder.startTable(1)
            addValue(builder, value)
            return endEncodeValueInt(builder)
        }
        fun startEncodeValueInt(builder: FlatBufferBuilder) = builder.startTable(1)
        fun addValue(builder: FlatBufferBuilder, value: Int) = builder.addInt(0, value, 0)
        fun endEncodeValueInt(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
