// automatically generated by the FlatBuffers compiler, do not modify

package org.luckypray.dexkit.schema

import com.google.flatbuffers.Constants
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.Table
import java.nio.ByteBuffer
import java.nio.ByteOrder

@Suppress("unused")
class EncodeValueLong : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : EncodeValueLong {
        __init(_i, _bb)
        return this
    }
    val value : Long
        get() {
            val o = __offset(4)
            return if(o != 0) bb.getLong(o + bb_pos) else 0L
        }
    fun mutateValue(value: Long) : Boolean {
        val o = __offset(4)
        return if (o != 0) {
            bb.putLong(o + bb_pos, value)
            true
        } else {
            false
        }
    }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_23_5_26()
        fun getRootAsEncodeValueLong(_bb: ByteBuffer): EncodeValueLong = getRootAsEncodeValueLong(_bb, EncodeValueLong())
        fun getRootAsEncodeValueLong(_bb: ByteBuffer, obj: EncodeValueLong): EncodeValueLong {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createEncodeValueLong(builder: FlatBufferBuilder, value: Long) : Int {
            builder.startTable(1)
            addValue(builder, value)
            return endEncodeValueLong(builder)
        }
        fun startEncodeValueLong(builder: FlatBufferBuilder) = builder.startTable(1)
        fun addValue(builder: FlatBufferBuilder, value: Long) = builder.addLong(0, value, 0L)
        fun endEncodeValueLong(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
