// automatically generated by the FlatBuffers compiler, do not modify

package org.luckypray.dexkit.schema

import com.google.flatbuffers.Constants
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.Table
import java.nio.ByteBuffer
import java.nio.ByteOrder

@Suppress("unused")
class EncodeValueString : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : EncodeValueString {
        __init(_i, _bb)
        return this
    }
    val value : String?
        get() {
            val o = __offset(4)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val valueAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(4, 1)
    fun valueInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 4, 1)
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_23_5_26()
        fun getRootAsEncodeValueString(_bb: ByteBuffer): EncodeValueString = getRootAsEncodeValueString(_bb, EncodeValueString())
        fun getRootAsEncodeValueString(_bb: ByteBuffer, obj: EncodeValueString): EncodeValueString {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createEncodeValueString(builder: FlatBufferBuilder, valueOffset: Int) : Int {
            builder.startTable(1)
            addValue(builder, valueOffset)
            return endEncodeValueString(builder)
        }
        fun startEncodeValueString(builder: FlatBufferBuilder) = builder.startTable(1)
        fun addValue(builder: FlatBufferBuilder, value: Int) = builder.addOffset(0, value, 0)
        fun endEncodeValueString(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}
