// automatically generated by the FlatBuffers compiler, do not modify

package org.luckypray.dexkit.schema

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
internal class `-LongRange` : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : `-LongRange` {
        __init(_i, _bb)
        return this
    }
    val min : Long
        get() {
            val o = __offset(4)
            return if(o != 0) bb.getLong(o + bb_pos) else 0L
        }
    fun mutateMin(min: Long) : Boolean {
        val o = __offset(4)
        return if (o != 0) {
            bb.putLong(o + bb_pos, min)
            true
        } else {
            false
        }
    }
    val max : Long
        get() {
            val o = __offset(6)
            return if(o != 0) bb.getLong(o + bb_pos) else 0L
        }
    fun mutateMax(max: Long) : Boolean {
        val o = __offset(6)
        return if (o != 0) {
            bb.putLong(o + bb_pos, max)
            true
        } else {
            false
        }
    }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_23_5_26()
        fun getRootAsLongRange(_bb: ByteBuffer): `-LongRange` = getRootAsLongRange(_bb, `-LongRange`())
        fun getRootAsLongRange(_bb: ByteBuffer, obj: `-LongRange`): `-LongRange` {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createLongRange(builder: FlatBufferBuilder, min: Long, max: Long) : Int {
            builder.startTable(2)
            addMax(builder, max)
            addMin(builder, min)
            return endLongRange(builder)
        }
        fun startLongRange(builder: FlatBufferBuilder) = builder.startTable(2)
        fun addMin(builder: FlatBufferBuilder, min: Long) = builder.addLong(0, min, 0L)
        fun addMax(builder: FlatBufferBuilder, max: Long) = builder.addLong(1, max, 0L)
        fun endLongRange(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}