// automatically generated by the FlatBuffers compiler, do not modify

package org.luckypray.dexkit.schema

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
internal class `-ParametersAnnotationMetaArrayHoler` : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : `-ParametersAnnotationMetaArrayHoler` {
        __init(_i, _bb)
        return this
    }
    fun annotationsArray(j: Int) : `-AnnotationMetaArrayHolder`? = annotationsArray(`-AnnotationMetaArrayHolder`(), j)
    fun annotationsArray(obj: `-AnnotationMetaArrayHolder`, j: Int) : `-AnnotationMetaArrayHolder`? {
        val o = __offset(4)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val annotationsArrayLength : Int
        get() {
            val o = __offset(4); return if (o != 0) __vector_len(o) else 0
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_23_5_26()
        fun getRootAsParametersAnnotationMetaArrayHoler(_bb: ByteBuffer): `-ParametersAnnotationMetaArrayHoler` = getRootAsParametersAnnotationMetaArrayHoler(_bb, `-ParametersAnnotationMetaArrayHoler`())
        fun getRootAsParametersAnnotationMetaArrayHoler(_bb: ByteBuffer, obj: `-ParametersAnnotationMetaArrayHoler`): `-ParametersAnnotationMetaArrayHoler` {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createParametersAnnotationMetaArrayHoler(builder: FlatBufferBuilder, annotationsArrayOffset: Int) : Int {
            builder.startTable(1)
            addAnnotationsArray(builder, annotationsArrayOffset)
            return endParametersAnnotationMetaArrayHoler(builder)
        }
        fun startParametersAnnotationMetaArrayHoler(builder: FlatBufferBuilder) = builder.startTable(1)
        fun addAnnotationsArray(builder: FlatBufferBuilder, annotationsArray: Int) = builder.addOffset(0, annotationsArray, 0)
        fun createAnnotationsArrayVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startAnnotationsArrayVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun endParametersAnnotationMetaArrayHoler(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}