// automatically generated by the FlatBuffers compiler, do not modify

package org.luckypray.dexkit.schema

@Suppress("unused")
class RetentionPolicyType private constructor() {
    companion object {
        const val Source: Byte = 0
        const val Class: Byte = 1
        const val Runtime: Byte = 2
    }
}
