// automatically generated by the FlatBuffers compiler, do not modify

package org.luckypray.dexkit.schema

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
internal class `-StringMatcher` : Table() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : `-StringMatcher` {
        __init(_i, _bb)
        return this
    }
    val value : String?
        get() {
            val o = __offset(4)
            return if (o != 0) {
                __string(o + bb_pos)
            } else {
                null
            }
        }
    val valueAsByteBuffer : ByteBuffer get() = __vector_as_bytebuffer(4, 1)
    fun valueInByteBuffer(_bb: ByteBuffer) : ByteBuffer = __vector_in_bytebuffer(_bb, 4, 1)
    val matchType : Byte
        get() {
            val o = __offset(6)
            return if(o != 0) bb.get(o + bb_pos) else 0
        }
    fun mutateMatchType(matchType: Byte) : Boolean {
        val o = __offset(6)
        return if (o != 0) {
            bb.put(o + bb_pos, matchType)
            true
        } else {
            false
        }
    }
    val ignoreCase : Boolean
        get() {
            val o = __offset(8)
            return if(o != 0) 0.toByte() != bb.get(o + bb_pos) else false
        }
    fun mutateIgnoreCase(ignoreCase: Boolean) : Boolean {
        val o = __offset(8)
        return if (o != 0) {
            bb.put(o + bb_pos, (if(ignoreCase) 1 else 0).toByte())
            true
        } else {
            false
        }
    }
    fun allOf(j: Int) : `-StringMatcher`? = allOf(`-StringMatcher`(), j)
    fun allOf(obj: `-StringMatcher`, j: Int) : `-StringMatcher`? {
        val o = __offset(10)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val allOfLength : Int
        get() {
            val o = __offset(10); return if (o != 0) __vector_len(o) else 0
        }
    fun anyOf(j: Int) : `-StringMatcher`? = anyOf(`-StringMatcher`(), j)
    fun anyOf(obj: `-StringMatcher`, j: Int) : `-StringMatcher`? {
        val o = __offset(12)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val anyOfLength : Int
        get() {
            val o = __offset(12); return if (o != 0) __vector_len(o) else 0
        }
    fun noneOf(j: Int) : `-StringMatcher`? = noneOf(`-StringMatcher`(), j)
    fun noneOf(obj: `-StringMatcher`, j: Int) : `-StringMatcher`? {
        val o = __offset(14)
        return if (o != 0) {
            obj.__assign(__indirect(__vector(o) + j * 4), bb)
        } else {
            null
        }
    }
    val noneOfLength : Int
        get() {
            val o = __offset(14); return if (o != 0) __vector_len(o) else 0
        }
    companion object {
        fun validateVersion() = Constants.FLATBUFFERS_23_5_26()
        fun getRootAsStringMatcher(_bb: ByteBuffer): `-StringMatcher` = getRootAsStringMatcher(_bb, `-StringMatcher`())
        fun getRootAsStringMatcher(_bb: ByteBuffer, obj: `-StringMatcher`): `-StringMatcher` {
            _bb.order(ByteOrder.LITTLE_ENDIAN)
            return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb))
        }
        fun createStringMatcher(builder: FlatBufferBuilder, valueOffset: Int, matchType: Byte, ignoreCase: Boolean, allOfOffset: Int, anyOfOffset: Int, noneOfOffset: Int) : Int {
            builder.startTable(6)
            addNoneOf(builder, noneOfOffset)
            addAnyOf(builder, anyOfOffset)
            addAllOf(builder, allOfOffset)
            addValue(builder, valueOffset)
            addIgnoreCase(builder, ignoreCase)
            addMatchType(builder, matchType)
            return endStringMatcher(builder)
        }
        fun startStringMatcher(builder: FlatBufferBuilder) = builder.startTable(6)
        fun addValue(builder: FlatBufferBuilder, value: Int) = builder.addOffset(0, value, 0)
        fun addMatchType(builder: FlatBufferBuilder, matchType: Byte) = builder.addByte(1, matchType, 0)
        fun addIgnoreCase(builder: FlatBufferBuilder, ignoreCase: Boolean) = builder.addBoolean(2, ignoreCase, false)
        fun addAllOf(builder: FlatBufferBuilder, allOf: Int) = builder.addOffset(3, allOf, 0)
        fun createAllOfVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startAllOfVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun addAnyOf(builder: FlatBufferBuilder, anyOf: Int) = builder.addOffset(4, anyOf, 0)
        fun createAnyOfVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startAnyOfVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun addNoneOf(builder: FlatBufferBuilder, noneOf: Int) = builder.addOffset(5, noneOf, 0)
        fun createNoneOfVector(builder: FlatBufferBuilder, data: IntArray) : Int {
            builder.startVector(4, data.size, 4)
            for (i in data.size - 1 downTo 0) {
                builder.addOffset(data[i])
            }
            return builder.endVector()
        }
        fun startNoneOfVector(builder: FlatBufferBuilder, numElems: Int) = builder.startVector(4, numElems, 4)
        fun endStringMatcher(builder: FlatBufferBuilder) : Int {
            val o = builder.endTable()
            return o
        }
    }
}