// automatically generated by the FlatBuffers compiler, do not modify

package org.luckypray.dexkit.schema

import com.google.flatbuffers.BaseVector
import com.google.flatbuffers.BooleanVector
import com.google.flatbuffers.ByteVector
import com.google.flatbuffers.Constants
import com.google.flatbuffers.DoubleVector
import com.google.flatbuffers.FlatBufferBuilder
import com.google.flatbuffers.FloatVector
import com.google.flatbuffers.LongVector
import com.google.flatbuffers.StringVector
import com.google.flatbuffers.Struct
import com.google.flatbuffers.Table
import com.google.flatbuffers.UnionVector
import java.nio.ByteBuffer
import java.nio.ByteOrder
import kotlin.math.sign

@Suppress("unused")
internal class `-UsingNumberMeta` : Struct() {

    fun __init(_i: Int, _bb: ByteBuffer)  {
        __reset(_i, _bb)
    }
    fun __assign(_i: Int, _bb: ByteBuffer) : `-UsingNumberMeta` {
        __init(_i, _bb)
        return this
    }
    val rawBits : ULong get() = bb.getLong(bb_pos + 0).toULong()
    fun mutateRawBits(rawBits: ULong) : ByteBuffer = bb.putLong(bb_pos + 0, rawBits.toLong())
    val opCode : UByte get() = bb.get(bb_pos + 8).toUByte()
    fun mutateOpCode(opCode: UByte) : ByteBuffer = bb.put(bb_pos + 8, opCode.toByte())
    companion object {
        fun createUsingNumberMeta(builder: FlatBufferBuilder, rawBits: ULong, opCode: UByte) : Int {
            builder.prep(8, 16)
            builder.pad(7)
            builder.putByte(opCode.toByte())
            builder.putLong(rawBits.toLong())
            return builder.offset()
        }
    }
}